### ISSUE TITLE
Error AdminTools

### ISSUE THREAD

**Issue by AngeloVenera** [DBinaghi/plugin-AdminTools#1]
Hi DBinaghi,

i have installed the AdminTools plugin, but when i click in "View public page" ia have this error:

Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, bool given in /srv/http/omeka-3.0.3/plugins/AdminTools/AdminToolsPlugin.php:254 Stack trace: #0 /srv/http/omeka-3.0.3/plugins/AdminTools/AdminToolsPlugin.php(254): in_array() #1 /srv/http/omeka-3.0.3/application/libraries/Omeka/Plugin/Broker.php(268): AdminToolsPlugin->filterPublicNavigationAdminBar() #2 /srv/http/omeka-3.0.3/application/libraries/globals.php(324): Omeka_Plugin_Broker->applyFilters() #3 /srv/http/omeka-3.0.3/application/libraries/globals.php(2705): apply_filters() #4 /srv/http/omeka-3.0.3/application/views/scripts/common/admin-bar.php(22): nav() #5 /srv/http/omeka-3.0.3/application/libraries/Omeka/View.php(114): include('...') #6 /srv/http/omeka-3.0.3/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run() #7 /srv/http/omeka-3.0.3/application/libraries/Zend/View/Helper/Partial.php(109): Zend_View_Abstract->render() #8 /srv/http/omeka-3.0.3/application/libraries/Zend/View/Abstract.php(349): Zend_View_Helper_Partial->partial() #9 /srv/http/omeka-3.0.3/application/libraries/globals.php(1666): Zend_View_Abstract->__call() #10 /srv/http/omeka-3.0.3/application/views/scripts/functions.php(24): common() #11 /srv/http/omeka-3.0.3/application/libraries/Omeka/Plugin/Broker.php(154): admin_bar() #12 /srv/http/omeka-3.0.3/application/libraries/globals.php(188): Omeka_Plugin_Broker->callHook() #13 /srv/http/omeka-3.0.3/themes/emiglio/common/header.php(44): fire_plugin_hook() #14 /srv/http/omeka-3.0.3/application/libraries/Omeka/View.php(114): include('...') #15 /srv/http/omeka-3.0.3/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run() #16 /srv/http/omeka-3.0.3/application/libraries/Zend/View/Helper/Partial.php(109): Zend_View_Abstract->render() #17 /srv/http/omeka-3.0.3/application/libraries/Zend/View/Abstract.php(349): Zend_View_Helper_Partial->partial() #18 /srv/http/omeka-3.0.3/application/libraries/globals.php(1666): Zend_View_Abstract->__call() #19 /srv/http/omeka-3.0.3/application/libraries/globals.php(1680): common() #20 /srv/http/omeka-3.0.3/themes/emiglio/items/show.php(1): head() #21 /srv/http/omeka-3.0.3/application/libraries/Omeka/View.php(114): include('...') #22 /srv/http/omeka-3.0.3/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run() #23 /srv/http/omeka-3.0.3/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render() #24 /srv/http/omeka-3.0.3/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript() #25 /srv/http/omeka-3.0.3/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render() #26 /srv/http/omeka-3.0.3/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch() #27 /srv/http/omeka-3.0.3/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch() #28 /srv/http/omeka-3.0.3/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch() #29 /srv/http/omeka-3.0.3/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch() #30 /srv/http/omeka-3.0.3/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch() #31 /srv/http/omeka-3.0.3/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run() #32 /srv/http/omeka-3.0.3/application/libraries/Omeka/Application.php(73): Zend_Application->run() #33 /srv/http/omeka-3.0.3/index.php(23): Omeka_Application->run() #34 {main} thrown in /srv/http/omeka-3.0.3/plugins/AdminTools/AdminToolsPlugin.php on line 254

**Comment by DBinaghi** [comment]
Hello.
Thanks for reporting this. 
I'm still working on the plugin, so there might be bugs, but this is quite weird. Could you please tell me which Omeka version are you using? And which version of the plugin?

**Comment by AngeloVenera** [comment]
Hi,

ignore my email, i have solved, was a configuration problem, thank you for answer.

Ciao Angelo

Da: DBinaghi ***@***.***>
Inviato: martedì 11 ottobre 2022 12:32
A: DBinaghi/plugin-AdminTools ***@***.***>
Cc: Angelo Venera ***@***.***>; Author ***@***.***>
Oggetto: Re: [DBinaghi/plugin-AdminTools] Error AdminTools (Issue #1)


Hello.
Thanks for reporting this.
I'm still working on the plugin, so there might be bugs, but this is quite weird. Could you please tell me which Omeka version are you using? And which version of the plugin?

**Comment by DBinaghi** [comment]
Solved, apparently.
